name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test:
    runs-on: ubuntu-latest

    name: Test compile

    steps:
      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake gcc lcov asciidoctor

      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Configure
        run: |
          cmake -B build -S . -Wdev -Wdeprecated \
            -DBUILD_TESTING=ON \
            -DCMAKE_BUILD_TYPE=RelWithDebInfo

      - name: Build
        run: cmake --build build --parallel

      - name: Test
        run: |
          cd build
          ctest --output-on-failure --verbose

      - name: Coverage
        run: make -C build coverage
